apiVersion: apps/v1
kind: Deployment
metadata:
  name: zaks-clouds-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zaks-clouds-manager
  template:
    metadata:
      labels:
        app: zaks-clouds-manager
    spec:
      containers:
        - name: zaks-clouds-manager-container
          image: cloudalb/zaks-clouds-manager:main
          volumeMounts:
              - name: zaks-clouds-manager-volume
                mountPath: /secret
          env:
            - name: ENVIRONMENT
              value: production
      volumes:
        - name: zaks-clouds-manager-volume
          secret:
            secretName: zaks-clouds-manager-secret-key
            items:
              - key: API_ID
                path: api_id
              - key: API_HASH
                path: api_hash
              - key: BOT_TOKEN
                path: bot_token
              - key: PHONE_NUMBER
                path: phone_number
